### ISSUE TITLE
🐛 Fix broken portfolio link in README

### ISSUE THREAD

**Issue by emmysteven** [KarenEfereyan/KarenEfereyan#1]
Hello 👋🏻

Nice to meet you Karen Efereyan, your profile here is great, however as I tried to view your [portfolio](https://karenefe.netlify.app/), I was greeted with this 👇🏻 
```
Not found - Request ID: 871d074d-eda9-4e2b-9991-1c6bb6205c38-27960186
```
It will be great if you fix this as soon as possible 😊

Regards!

**Comment by KarenEfereyan** [comment]
yes thanks. Im currently revamping it. It'll be up soon

**Comment by KarenEfereyan** [comment]
@emmysteven in case, you didn't know, ive updated my portfolio. It can be found here.  [portfolio](https://karenefe.netlify.app)
thanks for raising this issue. I'm closing it off since its been fixed,
